# Generated by Django 5.1.5 on 2025-01-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(default='sconoscuto', max_length=100),
            preserve_default=False,
        ),
    ]
